language: common-lisp
sudo: false
notifications:
  email: false

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=$HOME/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - COVERAGE_EXCLUDE=t
  matrix:
    - LISP=sbcl-bin COVERAGE=1
    - LISP=ccl-bin
    - LISP=ecl
    - LISP=allegro
    - LISP=abcl

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=abcl

install:
  # Install Roswell
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install fukamachi/rove
  - git clone https://github.com/fisxoj/validate ~/lisp/validate

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - ros --version
  - ros config

script:
  - rove sanity-clause.asd
